const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
assert(html.includes('Step 1.21'),'title must be Step 1.21');
const a=html.indexOf('function supportBonus'); const b=html.indexOf('function cleanOCR',a);
assert(a>=0&&b>0,'Step 1.21 scoring functions missing');
const ctx={};vm.createContext(ctx);vm.runInContext(html.slice(a,b)+';this.supportBonus=supportBonus;this.finalCandidateScore=finalCandidateScore;this.candidateDecision=candidateDecision;',ctx);
const {supportBonus,finalCandidateScore,candidateDecision}=ctx;
assert.equal(supportBonus(1,1),.04);
assert.equal(supportBonus(2,2),.08);
assert.equal(supportBonus(2,3),.06);
assert.equal(supportBonus(3,3),.12);
assert.equal(supportBonus(5,6),.10);
assert.equal(supportBonus(1,3),0);
assert(Math.abs(finalCandidateScore({avgNameScore:.63,confAvg:50,bestNameScore:.90,support:1,total:1,supportRatio:1})-.691)<.001);
assert(Math.abs(finalCandidateScore({avgNameScore:.63,confAvg:50,bestNameScore:.90,support:2,total:3,supportRatio:2/3})-.711)<.001);
assert(Math.abs(finalCandidateScore({avgNameScore:.63,confAvg:50,bestNameScore:.90,support:1,total:3,supportRatio:1/3})-.651)<.001);
assert(candidateDecision({final:.81,avgNameScore:.60,supportRatio:1,confAvg:30},null).level==='confirm');
assert(candidateDecision({final:.81,avgNameScore:.60,supportRatio:1,confAvg:60},null).level==='auto');
console.log('Step 1.21 support-bonus tests: passed');
