const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
assert(html.includes('Step 1.22'),'title must be Step 1.22');
assert(html.includes('総合スコア'),'display must expose total score');
const a=html.indexOf('function supportBonus'); const b=html.indexOf('function renderCandidates',a);
const ctx={}; vm.createContext(ctx); vm.runInContext(html.slice(a,b)+';this.supportBonus=supportBonus;this.finalCandidateScore=finalCandidateScore;this.totalCandidateScore=totalCandidateScore;this.candidateDecision=candidateDecision;',ctx);
const {supportBonus,finalCandidateScore,candidateDecision}=ctx;
const x={avgNameScore:.63,confAvg:50,bestNameScore:.90,support:3,total:3};
const s=finalCandidateScore(x);
assert(s && typeof s==='object','final score must expose components');
assert('charScore' in s && 'supportBonus' in s && 'ocrConfidence' in s && 'totalScore' in s,'score components missing');
assert(Math.abs(s.charScore-.576)<.001,'character component mismatch');
assert(Math.abs(s.supportBonus-.12)<.001,'support component mismatch');
assert(Math.abs(s.ocrConfidence-.075)<.001,'OCR component mismatch');
assert(Math.abs(s.totalScore-.771)<.001,'total score mismatch');
assert(Math.abs(finalCandidateScore({avgNameScore:.89,confAvg:88,bestNameScore:.89,support:1,total:1}).supportBonus-.04)<.001);
const d=candidateDecision({totalScore:.81,avgNameScore:.60,confAvg:60},null); assert(d.level==='auto','high-confidence single candidate should auto-confirm');
const d2=candidateDecision({totalScore:.81,avgNameScore:.60,confAvg:30},null); assert(d2.level==='confirm','low OCR confidence should require confirmation');
console.log('Step 1.22 RED expectations reached');
