const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const s=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
function setup(){const c={window:{}};vm.createContext(c);vm.runInContext('const KINDS='+s.match(/const KINDS=(\[.*?\]);/)[1]+';'+s.slice(s.indexOf('const CHARGE_BLADE_ENGINE_VERSION='),s.indexOf('function compareStep5Snapshot()')),c);
 const match=s.match(/<script id="horn-reference-ui">([\s\S]*?)<\/script>/);assert.ok(match,'reference UI must exist');
 const ids=['hhRefAttack','hhRefElement','hhRefElementHz','hhRefPerformance','hhRefNormalEcho','hhRefMelodyEcho','hhRefFixed','hhRefCalculate','hhRefOut'];const els=Object.fromEntries(ids.map(id=>[id,{value:'',textContent:'',addEventListener(event,fn){this[event]=fn;}}]));c.document={getElementById:id=>els[id]||null};vm.runInContext(match[1],c);return {c,els};}
function fill(e){for(const [id,value] of Object.entries({hhRefAttack:'200',hhRefElement:'100',hhRefElementHz:'20',hhRefPerformance:'0',hhRefNormalEcho:'2',hhRefMelodyEcho:'1',hhRefFixed:'1'}))e[id].value=value;}
test('reference UI computes explicit scenario and retains incomplete comparison warning',()=>{const {c,els}=setup();fill(els);els.hhRefCalculate.click();assert.match(els.hhRefOut.textContent,/55\.8/);assert.match(els.hhRefOut.textContent,/物理.*44/);assert.match(els.hhRefOut.textContent,/属性.*1\.8/);assert.match(els.hhRefOut.textContent,/本体攻撃を含みません/);assert.match(els.hhRefOut.textContent,/DPS/);assert.equal(c.window.BuildComparisonEngine.huntingHornComponentPlan().calculationReady,false);});
test('reference UI requires explicit zero instead of guessing blank event counts',()=>{const {els}=setup();fill(els);els.hhRefNormalEcho.value='';els.hhRefCalculate.click();assert.match(els.hhRefOut.textContent,/未入力/);assert.doesNotMatch(els.hhRefOut.textContent,/55\.8/);for(const bad of ['1.5','-1','Infinity','abc']){fill(els);els.hhRefMelodyEcho.value=bad;els.hhRefCalculate.click();assert.match(els.hhRefOut.textContent,/入力/);assert.doesNotMatch(els.hhRefOut.textContent,/参考合計/);}});
test('changing reference inputs clears stale result',()=>{const {els}=setup();fill(els);els.hhRefCalculate.click();els.hhRefAttack.value='210';els.hhRefAttack.input();assert.doesNotMatch(els.hhRefOut.textContent,/55\.8/);assert.match(els.hhRefOut.textContent,/再計算/);});
