const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),c={};vm.createContext(c);
vm.runInContext(html.slice(html.indexOf('function roundDamage2('),html.indexOf('function damage(){'))+html.slice(html.indexOf('function damageFromTechnique('),html.indexOf('function damageForMV('))+html.slice(html.indexOf('function damageFromValues('),html.indexOf('// v7.2.2-r21:',html.indexOf('function damageFromValues('))),c);
const ctx={attack:200,affinity:0,element:100,mv:100,hz:50,ehz:20,sharp:1,esharp:1,critBonus:0,elementCrit:false};
test('explicit zero MV and hitzones are never replaced with defaults',()=>{assert.equal(c.damageFromParams({...ctx,mv:0}).p,0);assert.equal(c.damageFromParams({...ctx,hz:0,ehz:0}).total,0);assert.equal(c.damageFromValues(200,0,100,100,0,0,1,1,0,0).total,0);});
test('negative affinity reduces expected physical damage in UI and comparison',()=>{assert.equal(c.damageFromParams({...ctx,affinity:-100}).total,77);assert.equal(c.damageFromValues(200,-100,100,100,50,20,1,1,0,0).total,77);});
test('critical skill level five and elemental crit share the same formula in comparison',()=>{assert.equal(c.damageFromParams({...ctx,affinity:50,critBonus:5,elementCrit:true}).total,122.4);assert.equal(c.damageFromValues(200,50,100,100,50,20,1,1,5,1).total,122.4);});
test('legacy per-hit element ratio and critical state survive ordinary hit calculation',()=>{assert.equal(c.damageFromTechnique({damageType:'physical',elementRatio:0},100,ctx).total,100);assert.equal(c.damageFromTechnique({damageType:'physical',elementRatio:1.5,criticalState:'noncritical'},100,{...ctx,affinity:100}).total,103);assert.equal(c.damageFromTechnique({damageType:'physical',elementRatio:1,criticalState:'negative-critical'},100,ctx).total,77);});
test('horn wave elemental hitzone uses percentage units and preserves zero element ratio',()=>{assert.equal(c.damageFromTechnique({damageType:'hunting-horn-wave',elementRatio:.3},5,ctx).total,10.6);assert.equal(c.damageFromTechnique({damageType:'hunting-horn-wave',elementRatio:0},5,ctx).total,10);});
